config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {registrations: 'users/registrations'}
  resources :users do
    resource :profile
  end
  resources :contacts
  get '/about' => 'pages#about'
  root 'pages#home'

end

app/models/contact.rb
class Contact < ActiveRecord::Base
    validates :name, presence: true
    validates :email, presence: true
end

app/models/plan.rb
class Plan < ActiveRecord::Base
    has_many :users
end

app/models/profile.rb
class Profile < ActiveRecord::Base
    belongs_to :user
    
    has_attached_file :avatar, styles: { medium: "300x300>", thumb: "100x100>" }, default_url: "/images/:style/missing.png"
    validates_attachment_content_type :avatar, content_type: /\Aimage\/.*\Z/
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  belongs_to :plan
  has_one :profile
  attr_accessor :stripe_card_token
  
  def save_with_payment
    if valid?
      customer = Stripe::Customer.create(description: email, plan: plan_id, source: stripe_card_token)
      self.stripe_customer_token = customer.id
      save!
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  
  protected
  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up) { |u| u.permit(:name, :stripe_card_token, :email, :password, :password_confirmation) }
  end
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
    def new
        @contact = Contact.new
    end
    
    def create
        @contact = Contact.new(contact_params)
        if @contact.save
            name = params[:contact][:name]
            email = params[:contact][:email]
            body = params[:contact][:comments]
            if(ContactMailer.contact_email(name,email,body))
                puts "Mailing succeeded"
                puts ContactMailer.contact_email(name,email,body)
            else
                puts "Mailing failed"
            end
            flash[:success] = "Message sent."
            redirect_to new_contact_path
        else
            flash[:danger] = "Error sending message."
            redirect_to new_contact_path
        end
    end
    private
        def contact_params
            params.require(:contact).permit(:name,:email,:comments) 
        end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
    def home
        @basic_plan = Plan.find(1)
        @premium_plan = Plan.find(2)
    end
    def about
    end
end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
    before_action :authenticate_user!
    before_action :only_current_user
    def new
        # form where each user can fill out their own profile
        @user = User.find(params[:user_id])
        @profile = Profile.new
    end
    
    def create
        @user = User.find(params[:user_id])
        @profile = @user.build_profile(profile_params)
        if @profile.save
            flash[:success] = "Profile created!"
            redirect_to user_path(params[:user_id])
        else
            render action :new
        end
    end
    
    def edit
        @user = User.find(params[:user_id])
        @profile = @user.profile
    end
    
    def update
        @user = User.find(params[:user_id])
        @profile = @user.profile
        if @profile.update_attributes(profile_params)
            flash[:success] = 'Profile updated!'
            redirect_to user_path(params[:user_id])
        else
            flash[:notice] = 'Failed to update profile.'
            render action :edit
        end
    end

    private
    def profile_params
        params.require(:profile).permit(:first_name,:last_name,:mailing_list,:description,:avatar)
    end
    
    def only_current_user
        @user = User.find(params[:user_id])
        unless @user == current_user
            flash[:notice] = 'You can only edit your own profile.'
            redirect_to(root_url)
        end
    end
end

app/controllers/users/registrations_controller.rb
class Users::RegistrationsController < Devise::RegistrationsController
    before_filter :select_plan, only: :new
    
    def create
        super do |resource|
            if params[:plan]
                resource.plan_id = params[:plan]
                if resource.plan_id == '2'
                    resource.save_with_payment
                else
                    resource.save
                end
            end
        end
    end
    
    private
        def select_plan

        end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    def show
        @user = User.find(params[:id])
        unless Profile.exists?(user_id: @user.id)
            if current_user.id == @user.id
                redirect_to new_user_profile_path(current_user.id)
            else
                flash[:notice] = "No profile found"
                redirect_to root_path
            end
        end
    end
    
    def index
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/contacts/new.html.erb
<div class="row">
    <%= form_for @contact do |f| %>
        <div class="col-md-4 col-md-offset-4">
            <div class="form-group">
                <%= f.label :name %>
                <%= f.text_field :name, class: "form-control" %>
            </div>
            <div class="form-group">
                <%= f.label :email %>
                <%= f.email_field :email, class: "form-control" %>
            </div>
            <div class="form-group">
                <%= f.label :comments %>
                <%= f.text_area :comments, class: "form-control" %>
            </div>
            <%= f.submit "Submit", class: "btn btn-default" %>
        </div>
    <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>The Mix Exchange</title>
    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'https://js.stripe.com/v2/', type = 'text/javascript' %>
    <%= javascript_include_tag 'application' %>
    <%= tag :meta, :name => 'stripe-key', :content => STRIPE_PUBLIC_KEY %>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <nav class="navbar navbar-inverse navbar-static-top" role="navigation">
      <div class="container">
        <div class="navbar_header">
          <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#main-nav-collapse">
            <span class="sr-only">Toggle navication</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <%= link_to root_path, class: "navbar-brand" do %>
            <i class="fa fa-toggle-right"></i>
            The Mix Exchange
          <% end %>
        </div>
        <div class="collapse navbar-collapse" id="main-nav-collapse">
          <div class="nav navbar-nav navbar-right">
            <% if current_user %>
              <%= button_to "Sign Out", destroy_user_session_path, method: :delete, class: 'btn btn-primary navbar-btn' %>
            <% else %>
              <%= link_to "Log In", new_user_session_path, class: 'btn btn-primary navbar-btn', method: :get %>
              <%= link_to "Sign Up", new_user_registration_path, class: 'btn btn-primary navbar-btn', method: :get %>
            <% end %>
          </div>
          <ul class="nav navbar-nav navbar-right">
            <li><%= link_to "About", about_path %></li>
            <li><%= link_to "Contact Us", new_contact_path  %></li>
            <% if current_user %>
              <li><%= link_to "Profile", user_path(current_user) %></li>
            <% end %>
          </ul>
        </div>
      </div>
    </nav>
    <div class="container">
      <% flash.each do |key,value| %>
        <%= content_tag :div, value, class: "alert alert-#{key}" %>
      <% end %>
      <%= yield %>
    </div>
  </body>
</html>

app/views/pages/_guest_front.html.erb
<div class="row">
    <div class="col-md-6">
        <div class = "advert-form well">
            <h2 class="text-center">Basic Membership</h2>
            <h4>Sign up for a free account and get basic access to the following features:</h4>
            <ul>
                <li>Thing 1</li>
                <li>Thing 2</li>
                <li>Last but not least, Thing 3!</li>
                <li style="text-decoration:line-through; color:#101010;">Literally nothing else</li>
            </ul>
            <%= link_to "Sign up for free", new_user_registration_path(plan: @basic_plan.id), class: 'btn btn-primary btn-lg btn-block signup-button' %>
        </div>
    </div>
    <div class="col-md-6">
        <div class = "advert-form well">
            <h2 class="text-center">Premium Membership</h2>
            <h4>Sign up for a premium account and get basic access to the following features:</h4>
            <ul>
                <li>Thing 1</li>
                <li>Thing 2</li>
                <li>Thing 3</li>
                <li>Literally nothing else</li>
            </ul>
            <%= link_to "Sign up for big bucks", new_user_registration_path(plan: @premium_plan.id), class: 'btn btn-success btn-lg btn-block signup-button' %>
        </div>
    </div>
</div>

app/views/pages/_member_front.html.erb
<ul class="nav nav-tabs nav-justified">
    <li role="navigation" class="active col-md-6">
        News
    </li>
    <li role="navigation" class="col-md-6">
        Blog
    </li>
</ul>

app/views/pages/about.html.erb
<h2>About The Mix Exchange</h2>
<p>This group is about mixing and sharing music. Each month we'll have a theme to provide a starting point for your mix, but you're welcome to take it in any direction you want. You'll be paired with another member of the group for the exchange, and you're encouraged to talk with them about their interests / preferred format before getting started on your mix.</p>
<p><h3>General outline of how each exchange will go:</h3>
	<ol>
		<li>Theme determined, group members paired</li>
		<li>Talk about details with your mix buddy (musical interests, best format for mix, etc.)</li>
		<li>Make and exchange!</li>
	</ol>
</p>
<p>CDs are highly recommended (way more fun / customizable than a playlist) but may not work for everyone, so they're not a requirement.</p>

<p><h3>Suggestions for making mixes</h3>
	<ol>
		<li>Be sensitive to your recipient&#8217;s tastes, but push boundaries here and there.</li>
		<li>Start with a few songs that fit well together, then expand from there and piece other songs in.</li>
		<li>Mix sounds/intensities up. Don&#8217;t hammer one point home too hard.</li>
		<li>Think about song positioning, transitions.</li>
		<li>From time to time, try to think of weird but interesting combinations of styles (electronic + punk, metal + folk)</li>
		<li>Dig deep. Go through your whole music library to see what you can find. Combine new and old when you can.</li>
		<li>Listen to the mix at least once, make decisions about what to cut and what to move.</li>
		<li>Inject your personality into the packaging + presentation.
		Provide a track list!</li>
	</ol>
</p>
<p><h3>Listener best practices</h3>
	<ol>
		<li>Keep an open mind. Avoid looking at the track list until you&#8217;ve listened to the mix and gotten a feel for things.</li>
		<li>Give feedback - in particular about what you liked, but also about what you didn’t care for.</li>
	</ol>
</p>

<p><h3>PAQ (Preemptively Answered Questions)</h3>
	<ol>
		<li>What if I really want to give someone a mix?<br>
		- Ask them! Nobody will know.</li>
		<li>What if I really want a mix from a specific person?<br>
		- Ask them! Nobody will know.</li>
		<li>What if I don’t want to / can’t participate in an exchange?<br>
		- Tell me! We'll need to get your mix buddy re-paired with someone.</li>
	</ol>
</p>

app/views/pages/home.html.erb
<div class="container col-md-12">
    <h1 class="text-center">Welcome to The Mix Exchange</h1>
    <p class="text-center">you fucking hipster</p>
</div>
<div class="container">
</div>

<% if user_signed_in? %>
    <%= render "member_front" %>
<% else %>
    <%= render "guest_front" %>
<% end %>

app/views/profiles/_form.html.erb
<%= form_for @profile, url: user_profile_path, html: { multipart: true } do |x| %>
    <div class="form-group">
        <%= x.label :first_name %>
        <%= x.text_field :first_name, class: "form-control" %>
    </div>
    <div class="form-group">
        <%= x.label :last_name %>
        <%= x.text_field :last_name, class: "form-control" %>
    </div>
    <div class="form-group">
        <%= x.label :mailing_address %>
        <%= x.text_field :mailing_address, class: "form-control" %>
    </div>
    <div class="form-group">
        <%= x.label :description %>
        <%= x.text_area :description, class: "form-control" %>
    </div>
    <div class="form-group">
        <%= x.label :avatar %>
        <%= x.file_field :avatar %>
    </div>
    <div class="form-group">
        <%= x.submit "Create your profile",class: "btn btn-primary" %>
    </div>
<% end %>

app/views/profiles/edit.html.erb
<div class="row">
    <div class="col-md-6 col-md-offset-3">
        <h1 class="text-center">Edit your profile!</h1>
        <p class="text-center">Come on then.</p>
        <div class="well">
            <%= render 'form' %>
        </div>
    </div>
</div>

app/views/profiles/new.html.erb
<div class="row">
    <div class="col-md-6 col-md-offset-3">
        <h1 class="text-center">Create your profile!</h1>
        <p class="text-center">Hurry up now.</p>
        <div class="well">
            <%= render 'form' %>
        </div>
    </div>
</div>

app/views/users/show.html.erb
<div class="col-md-12">
    <div class = 'well sidebar col-md-3 bk'>
        <%= image_tag @user.profile.avatar, class: 'img-thumbnail profile-photo' %>
        <div>
            Participation stats will go here.
        </div>
        <div>
            Mix photos sent will go here.
        </div>
        <div>
            Mix photos received will go here.
        </div>
    </div>
    <div class = 'content col-md-9'>
        <% if current_user %>
            <%= link_to "Edit your profile!", edit_user_profile_path(current_user), class: 'btn btn-success pull-right' if current_user.id == params[:id].to_f %>
        <% end %>
        <div class="page-header">
            <h2>
                <%= @user.profile.first_name %> <%= @user.profile.last_name %>
            </h2>
        </div>
        <div>
            <p>
                <%= @user.profile.description %>
            </p>
        </div>
    </div>
</div>